[package]
name = "kernelbase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "kernelbase façade: internal Win32 implementation"

[dependencies]
winabi.workspace = true
ntdll.workspace = true
nt-file.workspace = true
nt-thread.workspace = true
nt-sync.workspace = true
tracing.workspace = true

# Só para o teste de ciclo TLS (contexto mínimo real).
[dev-dependencies]
nt-object.workspace = true
nt-memory.workspace = true
